import type { Metadata } from "next";
import { Poppins, Volkhov, Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { PopUpCookie } from "@/components/Pop-up/Cookie";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const volkhov = Volkhov({
  variable: "--font-volkhov",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Xceltutors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${volkhov.variable} ${inter.variable} antialiased`}
      >
        <div className="relative w-full min-h-screen flex flex-col items-center space-y-[4rem]
     bg-[#f8f8f8] shadow-glow overflow-hidden">
          <Header />
          <main className="w-full flex flex-col space-y-[4rem] relative z-10">
            {children}
          </main>
          <Footer />
          <PopUpCookie />
        </div>
      </body>
    </html>
  );
}
